twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        # point this wherever your css files live
        '%kernel.project_dir%/public/css': css
        '%kernel.project_dir%/public/fonts': fonts
        '%kernel.project_dir%/public/images': images
    globals:
        images_path: '%kernel.project_dir%/public/images'

